**Species name extraction**

In [10]:
import json
import requests

import pandas as pd

In [11]:
from gbif_species_name_match import (extract_gbif_species_names_info, 
                                     extract_species_information,
                                     extract_gbif_accepted_key)

In [13]:
redListunVal = pd.read_csv ("unvalidatedRedListDwCNotebookOutputOutputRematch2.csv")

In [14]:
redListunVal.head()

,UniqueID,TaxonomicGroup,YearPublished,Kingdom,verbatimScientificName,scientificName,gbifapi_species,vernacularname,RLCAsPublished,RLC,...,rightsHolder,accessRights,datasetName,locationID,locality,countryCode,occurrencestatus,threadStatus,RLC code Translated term,gbifapi_rank
0,INBO:RL:NONVAL:AMP:1996:1,Amphibians,1996,Animalia,Alytes obstetricans,Alytes obstetricans,Alytes obstetricans,Vroedmeesterpad,Bedreigd,EN,...,INBO,http://www.inbo.be/en/norms-for-data-use,UnValidated Red Lists of Flanders,http://marineregions.org/mrgid/2469,Flanders,BE,present,Endangered (EN),Endangered (EN) / EN,SPECIES
1,INBO:RL:NONVAL:AMP:1996:10,Amphibians,1996,Animalia,Salamandra salamandra,Salamandra salamandra,Salamandra salamandra,Vuursalamander,Kwetsbaar,VU,...,INBO,http://www.inbo.be/en/norms-for-data-use,UnValidated Red Lists of Flanders,http://marineregions.org/mrgid/2469,Flanders,BE,present,Vulnerable (VU),Vulnerable (VU) / VU,SPECIES
2,INBO:RL:NONVAL:AMP:1996:11,Amphibians,1996,Animalia,Triturus alpestris,Triturus alpestris,Ichthyosaura alpestris,Alpenwatersalamander,Momenteel niet bedreigd,LC,...,INBO,http://www.inbo.be/en/norms-for-data-use,UnValidated Red Lists of Flanders,http://marineregions.org/mrgid/2469,Flanders,BE,present,Least Concern (LC),Least Concern (LC) / LC,SPECIES
3,INBO:RL:NONVAL:AMP:1996:12,Amphibians,1996,Animalia,Triturus cristatus,Triturus cristatus,Triturus cristatus,Kamsalamander,Zeldzaam,NT,...,INBO,http://www.inbo.be/en/norms-for-data-use,UnValidated Red Lists of Flanders,http://marineregions.org/mrgid/2469,Flanders,BE,present,Near Threatened (NT),Near Threatened (NT) / NT,SPECIES
4,INBO:RL:NONVAL:AMP:1996:13,Amphibians,1996,Animalia,Triturus helveticus,Triturus helveticus,Lissotriton helveticus,Vinpootsalamander,Zeldzaam,NT,...,INBO,http://www.inbo.be/en/norms-for-data-use,UnValidated Red Lists of Flanders,http://marineregions.org/mrgid/2469,Flanders,BE,present,Near Threatened (NT),Near Threatened (NT) / NT,SPECIES

In [38]:
updated_tsv = extract_species_information("unvalidatedRedListDwCNotebookOutputRefinerematch1.csv", 
                                          output=None,                              
                                          api_terms=["usageKey", 
                                                     "scientificName", 
                                                     "canonicalName",
                                                     "status", 
                                                     "rank", 
                                                     "matchType", 
                                                     "confidence"],
                                         )

Using columns scientificName and Kingdom for API request.

In [15]:
unvalidatedList = extract_species_information("unvalidatedRedListDwCNotebookOutputOutputRematch2.csv", output=None, api_terms="all")

Using columns scientificName and Kingdom for API request.

In [40]:
updated_tsv.head()

,UniqueID,TaxonomicGroup,YearPublished,Kingdom,scientificName,vernacularname,RLCAsPublished,RLC,RLCEurope,Criteria,...,threadStatus,gbifapi_usageKey,gbifapi_scientificName,gbifapi_canonicalName,gbifapi_status,gbifapi_rank,gbifapi_matchType,gbifapi_confidence,gbifapi_acceptedKey,gbifapi_acceptedScientificName
0,INBO:RL:NONVAL:AMP:1996:1,Amphibians,1996,Animalia,Alytes obstetricans,Vroedmeesterpad,Bedreigd,EN,LC,Regional,...,Endangered (EN),2426612,"Alytes obstetricans (Laurenti, 1768)",Alytes obstetricans,ACCEPTED,SPECIES,EXACT,100,2426612,"Alytes obstetricans (Laurenti, 1768)"
1,INBO:RL:NONVAL:AMP:1996:10,Amphibians,1996,Animalia,Salamandra salamandra,Vuursalamander,Kwetsbaar,VU,LC,Regional,...,Vulnerable (VU),2431776,"Salamandra salamandra (Linnaeus, 1758)",Salamandra salamandra,ACCEPTED,SPECIES,EXACT,100,2431776,"Salamandra salamandra (Linnaeus, 1758)"
2,INBO:RL:NONVAL:AMP:1996:11,Amphibians,1996,Animalia,Triturus alpestris,Alpenwatersalamander,Momenteel niet bedreigd,LC,LC,Regional,...,Least Concern (LC),2431785,"Triturus alpestris (Laurenti, 1768)",Triturus alpestris,SYNONYM,SPECIES,EXACT,100,2431783,"Ichthyosaura alpestris (Laurenti, 1768)"
3,INBO:RL:NONVAL:AMP:1996:12,Amphibians,1996,Animalia,Triturus cristatus,Kamsalamander,Zeldzaam,NT,LC,Regional,...,Near Threatened (NT),2431885,"Triturus cristatus (Laurenti, 1768)",Triturus cristatus,ACCEPTED,SPECIES,EXACT,100,2431885,"Triturus cristatus (Laurenti, 1768)"
4,INBO:RL:NONVAL:AMP:1996:13,Amphibians,1996,Animalia,Triturus helveticus,Vinpootsalamander,Zeldzaam,NT,LC,Regional,...,Near Threatened (NT),2431911,"Triturus helveticus (Razoumovsky, 1789)",Triturus helveticus,SYNONYM,SPECIES,EXACT,100,5218410,"Lissotriton helveticus (Razoumovsky, 1789)"

In [16]:
unvalidatedList.head()

,UniqueID,TaxonomicGroup,YearPublished,Kingdom,verbatimScientificName,scientificName,gbifapi_species,vernacularname,RLCAsPublished,RLC,...,gbifapi_orderKey,gbifapi_phylum,gbifapi_phylumKey,gbifapi_rank,gbifapi_scientificName,gbifapi_species,gbifapi_speciesKey,gbifapi_status,gbifapi_synonym,gbifapi_usageKey
0,INBO:RL:NONVAL:AMP:1996:1,Amphibians,1996,Animalia,Alytes obstetricans,Alytes obstetricans,Alytes obstetricans,Vroedmeesterpad,Bedreigd,EN,...,952,Chordata,44,SPECIES,"Alytes obstetricans (Laurenti, 1768)",Alytes obstetricans,2426612,ACCEPTED,False,2426612
1,INBO:RL:NONVAL:AMP:1996:10,Amphibians,1996,Animalia,Salamandra salamandra,Salamandra salamandra,Salamandra salamandra,Vuursalamander,Kwetsbaar,VU,...,953,Chordata,44,SPECIES,"Salamandra salamandra (Linnaeus, 1758)",Salamandra salamandra,2431776,ACCEPTED,False,2431776
2,INBO:RL:NONVAL:AMP:1996:11,Amphibians,1996,Animalia,Triturus alpestris,Triturus alpestris,Ichthyosaura alpestris,Alpenwatersalamander,Momenteel niet bedreigd,LC,...,953,Chordata,44,SPECIES,"Triturus alpestris (Laurenti, 1768)",Ichthyosaura alpestris,2431783,SYNONYM,True,2431785
3,INBO:RL:NONVAL:AMP:1996:12,Amphibians,1996,Animalia,Triturus cristatus,Triturus cristatus,Triturus cristatus,Kamsalamander,Zeldzaam,NT,...,953,Chordata,44,SPECIES,"Triturus cristatus (Laurenti, 1768)",Triturus cristatus,2431885,ACCEPTED,False,2431885
4,INBO:RL:NONVAL:AMP:1996:13,Amphibians,1996,Animalia,Triturus helveticus,Triturus helveticus,Lissotriton helveticus,Vinpootsalamander,Zeldzaam,NT,...,953,Chordata,44,SPECIES,"Triturus helveticus (Razoumovsky, 1789)",Lissotriton helveticus,5218410,SYNONYM,True,2431911

In [17]:
unvalidatedList.to_csv("unvalidatedRedListDwCNotebookOutputOutputRematch2.csv", index=False)