In [1]:
import json
import requests

import pandas as pd

In [2]:
temp = requests.get("http://api.gbif.org/v1/species/match?verbose=false&kingdom=Plantae&name=Heracleum%20mantegazziaum&strict=false")

In [3]:
temp.json()

{'canonicalName': 'Heracleum mantegazzianum',
 'class': 'Magnoliopsida',
 'classKey': 220,
 'confidence': 96,
 'family': 'Apiaceae',
 'familyKey': 6720,
 'genus': 'Heracleum',
 'genusKey': 3034824,
 'kingdom': 'Plantae',
 'kingdomKey': 6,
 'matchType': 'FUZZY',
 'order': 'Apiales',
 'orderKey': 1351,
 'phylum': 'Tracheophyta',
 'phylumKey': 7707728,
 'rank': 'SPECIES',
 'scientificName': 'Heracleum mantegazzianum Sommier & Levier',
 'species': 'Heracleum mantegazzianum',
 'speciesKey': 3034825,
 'status': 'ACCEPTED',
 'synonym': False,
 'usageKey': 3034825}

In [4]:
from gbif_species_name_match import (extract_gbif_species_names_info, 
                                     extract_species_information,
                                     extract_gbif_accepted_key)

In [5]:
redListVal = pd.read_csv("ValidatedRedListsSourceRefine.csv")

In [6]:
redListVal.head()

,UniqueID,TaxonomicGroup,YearPublished,Kingdom,Phylum,Class,Order,Family,Genus,Species,...,IUCNCriteria,Reference,Biome,Biotope1,Biotope2,Cuddliness,Lifespan,Mobility,NutrientLevel,Spine
0,INBO:RL:VAL:AMP:2013:15,Amphibians,2013,Animalia,Chordata,Amphibia,Anura,Alytidae,Alytes,obstetricans,...,B2a(i)b(iii)c(iv);C2a(i),Jooris_etal_2012,Aquatic,Limnophilous,NaN,Low,Longlived,Low,Mesotrophic,Vertebrate
1,INBO:RL:VAL:AMP:2013:16,Amphibians,2013,Animalia,Chordata,Amphibia,Anura,Bombinatoridae,Bombina,variegata,...,NaN,Jooris_etal_2012,Aquatic,Limnophilous,NaN,Low,Longlived,Low,Mesotrophic,Vertebrate
2,INBO:RL:VAL:AMP:2013:17,Amphibians,2013,Animalia,Chordata,Amphibia,Anura,Bufonidae,Bufo,bufo,...,NaN,Jooris_etal_2012,Aquatic,Eurytopic,NaN,Low,Longlived,Low,Eutrophic,Vertebrate
3,INBO:RL:VAL:AMP:2013:18,Amphibians,2013,Animalia,Chordata,Amphibia,Anura,Bufonidae,Bufo,calamita,...,B2a(i);C2a(i),Jooris_etal_2012,Aquatic,Heathlands,NaN,Low,Longlived,Low,Oligotrophic,Vertebrate
4,INBO:RL:VAL:AMP:2013:19,Amphibians,2013,Animalia,Chordata,Amphibia,Anura,Hylidae,Hyla,arborea,...,B2a(i)b(iii)c(iv);C2a(i),Jooris_etal_2012,Aquatic,Limnophilous,NaN,Low,Longlived,Low,Mesotrophic,Vertebrate

In [14]:
updated_tsv = extract_species_information("ValidatedRedListsSourceRefine.csv", 
                                          output=None,                              
                                          api_terms=["usageKey", 
                                                     "scientificName", 
                                                     "canonicalName",
                                                     "status", 
                                                     "rank", 
                                                     "matchType", 
                                                     "confidence"],
                                         )

Using columns scientificName and Kingdom for API request.

In [17]:
validatedList = extract_species_information("ValidatedRedListsSourceRefine.csv", output=None, api_terms="all")

Using columns scientificName and Kingdom for API request.

In [16]:
updated_tsv.head()

,UniqueID,TaxonomicGroup,YearPublished,Kingdom,Phylum,Class,Order,Family,Genus,Species,...,Spine,gbifapi_usageKey,gbifapi_scientificName,gbifapi_canonicalName,gbifapi_status,gbifapi_rank,gbifapi_matchType,gbifapi_confidence,gbifapi_acceptedKey,gbifapi_acceptedScientificName
0,INBO:RL:VAL:AMP:2013:15,Amphibians,2013,Animalia,Chordata,Amphibia,Anura,Alytidae,Alytes,obstetricans,...,Vertebrate,2426612,"Alytes obstetricans (Laurenti, 1768)",Alytes obstetricans,ACCEPTED,SPECIES,EXACT,100,2426612,"Alytes obstetricans (Laurenti, 1768)"
1,INBO:RL:VAL:AMP:2013:16,Amphibians,2013,Animalia,Chordata,Amphibia,Anura,Bombinatoridae,Bombina,variegata,...,Vertebrate,2423435,"Bombina variegata (Linnaeus, 1758)",Bombina variegata,ACCEPTED,SPECIES,EXACT,100,2423435,"Bombina variegata (Linnaeus, 1758)"
2,INBO:RL:VAL:AMP:2013:17,Amphibians,2013,Animalia,Chordata,Amphibia,Anura,Bufonidae,Bufo,bufo,...,Vertebrate,5217160,"Bufo bufo (Linnaeus, 1758)",Bufo bufo,ACCEPTED,SPECIES,EXACT,100,5217160,"Bufo bufo (Linnaeus, 1758)"
3,INBO:RL:VAL:AMP:2013:18,Amphibians,2013,Animalia,Chordata,Amphibia,Anura,Bufonidae,Bufo,calamita,...,Vertebrate,5216775,"Bufo calamita Laurenti, 1768",Bufo calamita,SYNONYM,SPECIES,EXACT,100,2422507,"Epidalea calamita (Laurenti, 1768)"
4,INBO:RL:VAL:AMP:2013:19,Amphibians,2013,Animalia,Chordata,Amphibia,Anura,Hylidae,Hyla,arborea,...,Vertebrate,2427573,"Hyla arborea (Linnaeus, 1758)",Hyla arborea,ACCEPTED,SPECIES,EXACT,100,2427573,"Hyla arborea (Linnaeus, 1758)"

In [18]:
validatedList.head()

,UniqueID,TaxonomicGroup,YearPublished,Kingdom,Phylum,Class,Order,Family,Genus,Species,...,gbifapi_orderKey,gbifapi_phylum,gbifapi_phylumKey,gbifapi_rank,gbifapi_scientificName,gbifapi_species,gbifapi_speciesKey,gbifapi_status,gbifapi_synonym,gbifapi_usageKey
0,INBO:RL:VAL:AMP:2013:15,Amphibians,2013,Animalia,Chordata,Amphibia,Anura,Alytidae,Alytes,obstetricans,...,952,Chordata,44,SPECIES,"Alytes obstetricans (Laurenti, 1768)",Alytes obstetricans,2426612,ACCEPTED,False,2426612
1,INBO:RL:VAL:AMP:2013:16,Amphibians,2013,Animalia,Chordata,Amphibia,Anura,Bombinatoridae,Bombina,variegata,...,952,Chordata,44,SPECIES,"Bombina variegata (Linnaeus, 1758)",Bombina variegata,2423435,ACCEPTED,False,2423435
2,INBO:RL:VAL:AMP:2013:17,Amphibians,2013,Animalia,Chordata,Amphibia,Anura,Bufonidae,Bufo,bufo,...,952,Chordata,44,SPECIES,"Bufo bufo (Linnaeus, 1758)",Bufo bufo,5217160,ACCEPTED,False,5217160
3,INBO:RL:VAL:AMP:2013:18,Amphibians,2013,Animalia,Chordata,Amphibia,Anura,Bufonidae,Bufo,calamita,...,952,Chordata,44,SPECIES,"Bufo calamita Laurenti, 1768",Epidalea calamita,2422507,SYNONYM,True,5216775
4,INBO:RL:VAL:AMP:2013:19,Amphibians,2013,Animalia,Chordata,Amphibia,Anura,Hylidae,Hyla,arborea,...,952,Chordata,44,SPECIES,"Hyla arborea (Linnaeus, 1758)",Hyla arborea,2427573,ACCEPTED,False,2427573

In [19]:
validatedList.to_csv("validatedRedListDwC.csv", index=False)