# PINK libellen data

In [2]:
import pandas as pd

In [3]:
!head Libel_PINK_original_csv.csv

head wordt niet herkend als een interne
of externe opdracht, programma of batchbestand.

In [4]:
data = pd.read_csv(
    'Libel_PINK_original_csv.csv',
    delimiter=';',
    dtype=object
)

In [5]:
# Check the null values
# data.isnull()

# check the none null vaues
# data.notnull()

In [5]:
data.head()

,WaarnemerNaam1,WaarnemerNaam2,WaarnemerNaam3,PoelCode,Datum,SoortNaamNl,Exuvium,Teneral,Mannetje,Wijfje,Adult onbepaald,Tandem,Eiafzettend,Opmerking_Poel,Opmerking_Soort
0,Ward Vercruysse,Simon Feys,NaN,BDH_004,16/06/2010,Azuurwaterjuffer,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
1,Simon Feys,Ward Vercruysse,NaN,BDH_004,19/07/2010,Bloedrode heidelibel,NaN,NaN,8,3,NaN,NaN,NaN,NaN,"Tandems gezien, niet geteld"
2,Simon Feys,Ward Vercruysse,NaN,BDH_004,19/07/2010,Blauwe glazenmaker,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
3,Ward Vercruysse,NaN,NaN,BDH_005,19/05/2014,Lantaarntje,NaN,NaN,NaN,1,NaN,NaN,x,NaN,NaN
4,Ward Vercruysse,NaN,NaN,BDH_005,19/05/2014,Azuurwaterjuffer,NaN,NaN,7,NaN,NaN,3,NaN,NaN,NaN

In [7]:
data.describe()

,WaarnemerNaam1,WaarnemerNaam2,WaarnemerNaam3,PoelCode,Datum,SoortNaamNl,Exuvium,Teneral,Mannetje,Wijfje,Adult onbepaald,Tandem,Eiafzettend,Opmerking_Poel,Opmerking_Soort
count,2668,187,12,2668,2668,2668,6,266,2057,960,534,227,349,82,552
unique,3,2,2,205,92,38,4,25,87,41,42,33,1,16,2
top,Ward Vercruysse,Ward Vercruysse,David Berten,NOD_001,30/06/2008,Lantaarntje,1,1,1,1,1,1,x,ZWI_135_146,"Tandems gezien, niet geteld"
freq,2107,109,8,88,109,430,3,141,859,499,191,102,349,31,548

In [7]:
data.tail()

,WaarnemerNaam1,WaarnemerNaam2,WaarnemerNaam3,PoelCode,Datum,SoortNaamNl,Exuvium,Teneral,Mannetje,Wijfje,Adult onbepaald,Tandem,Eiafzettend,Opmerking_Poel,Opmerking_Soort
2663,Ward Vercruysse,NaN,NaN,ZWI_165,13/08/2014,Zwervende pantserjuffer,NaN,NaN,2,1,NaN,NaN,NaN,NaN,NaN
2664,Ward Vercruysse,NaN,NaN,ZWI_166,2/06/2014,Azuurwaterjuffer,NaN,NaN,6,NaN,NaN,2,NaN,NaN,NaN
2665,Ward Vercruysse,NaN,NaN,ZWI_166,2/06/2014,Gaffelwaterjuffer,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
2666,Ward Vercruysse,NaN,NaN,ZWI_166,1/07/2014,Bloedrode heidelibel,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
2667,Ward Vercruysse,NaN,NaN,ZWI_166,1/09/2014,Bruinrode heidelibel,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN

In [8]:
data["Datum"] = pd.to_datetime(data["Datum"])

In [9]:
data["Datum"][0]

Timestamp('2010-06-16 00:00:00')

In [10]:
data.columns

Index(['WaarnemerNaam1', 'WaarnemerNaam2', 'WaarnemerNaam3', 'PoelCode',
       'Datum', 'SoortNaamNl', 'Exuvium', 'Teneral', 'Mannetje', 'Wijfje',
       'Adult onbepaald', 'Tandem', 'Eiafzettend', 'Opmerking_Poel',
       'Opmerking_Soort'],
      dtype='object')

In [11]:
data.loc[1, ['WaarnemerNaam1', 'WaarnemerNaam2', 'WaarnemerNaam3']]

WaarnemerNaam1         Simon Feys
WaarnemerNaam2    Ward Vercruysse
WaarnemerNaam3                NaN
Name: 1, dtype: object

In [12]:
def combine_waarnemers(row):
    """ """
    names = row.loc[['WaarnemerNaam1', 'WaarnemerNaam2', 'WaarnemerNaam3']].dropna().values.tolist()
    return " | ".join(names)

In [13]:
data["recordedBy"] = data.apply(combine_waarnemers, axis=1)

In [14]:
data["identifiedBy"] = data.apply(combine_waarnemers, axis=1)

In [15]:
data[['WaarnemerNaam1', 'WaarnemerNaam2', 'WaarnemerNaam3', "recordedBy", "identifiedBy"]].head()

,WaarnemerNaam1,WaarnemerNaam2,WaarnemerNaam3,recordedBy,identifiedBy
0,Ward Vercruysse,Simon Feys,NaN,Ward Vercruysse | Simon Feys,Ward Vercruysse | Simon Feys
1,Simon Feys,Ward Vercruysse,NaN,Simon Feys | Ward Vercruysse,Simon Feys | Ward Vercruysse
2,Simon Feys,Ward Vercruysse,NaN,Simon Feys | Ward Vercruysse,Simon Feys | Ward Vercruysse
3,Ward Vercruysse,NaN,NaN,Ward Vercruysse,Ward Vercruysse
4,Ward Vercruysse,NaN,NaN,Ward Vercruysse,Ward Vercruysse

In [16]:
data.head ()

,WaarnemerNaam1,WaarnemerNaam2,WaarnemerNaam3,PoelCode,Datum,SoortNaamNl,Exuvium,Teneral,Mannetje,Wijfje,Adult onbepaald,Tandem,Eiafzettend,Opmerking_Poel,Opmerking_Soort,recordedBy,identifiedBy
0,Ward Vercruysse,Simon Feys,NaN,BDH_004,2010-06-16,Azuurwaterjuffer,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse | Simon Feys,Ward Vercruysse | Simon Feys
1,Simon Feys,Ward Vercruysse,NaN,BDH_004,2010-07-19,Bloedrode heidelibel,NaN,NaN,8,3,NaN,NaN,NaN,NaN,"Tandems gezien, niet geteld",Simon Feys | Ward Vercruysse,Simon Feys | Ward Vercruysse
2,Simon Feys,Ward Vercruysse,NaN,BDH_004,2010-07-19,Blauwe glazenmaker,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,Simon Feys | Ward Vercruysse,Simon Feys | Ward Vercruysse
3,Ward Vercruysse,NaN,NaN,BDH_005,2014-05-19,Lantaarntje,NaN,NaN,NaN,1,NaN,NaN,x,NaN,NaN,Ward Vercruysse,Ward Vercruysse
4,Ward Vercruysse,NaN,NaN,BDH_005,2014-05-19,Azuurwaterjuffer,NaN,NaN,7,NaN,NaN,3,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse

In [17]:
data["institutionCode"] = "INBO"

In [18]:
data.rename(columns={"PoelCode":"locationID",
                     "Datum":"eventDate",
                    "SoortNaamNL":"vernacularName",})

,WaarnemerNaam1,WaarnemerNaam2,WaarnemerNaam3,locationID,eventDate,SoortNaamNl,Exuvium,Teneral,Mannetje,Wijfje,Adult onbepaald,Tandem,Eiafzettend,Opmerking_Poel,Opmerking_Soort,recordedBy,identifiedBy,institutionCode
0,Ward Vercruysse,Simon Feys,NaN,BDH_004,2010-06-16,Azuurwaterjuffer,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse | Simon Feys,Ward Vercruysse | Simon Feys,INBO
1,Simon Feys,Ward Vercruysse,NaN,BDH_004,2010-07-19,Bloedrode heidelibel,NaN,NaN,8,3,NaN,NaN,NaN,NaN,"Tandems gezien, niet geteld",Simon Feys | Ward Vercruysse,Simon Feys | Ward Vercruysse,INBO
2,Simon Feys,Ward Vercruysse,NaN,BDH_004,2010-07-19,Blauwe glazenmaker,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,Simon Feys | Ward Vercruysse,Simon Feys | Ward Vercruysse,INBO
3,Ward Vercruysse,NaN,NaN,BDH_005,2014-05-19,Lantaarntje,NaN,NaN,NaN,1,NaN,NaN,x,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
4,Ward Vercruysse,NaN,NaN,BDH_005,2014-05-19,Azuurwaterjuffer,NaN,NaN,7,NaN,NaN,3,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
5,Ward Vercruysse,NaN,NaN,BDH_005,2014-05-19,Platbuik,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
6,Ward Vercruysse,NaN,NaN,BDH_005,2014-02-07,Azuurwaterjuffer,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
7,Ward Vercruysse,NaN,NaN,BDH_005,2014-02-07,Bloedrode heidelibel,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
8,Ward Vercruysse,NaN,NaN,BDH_005,2014-02-07,Bruinrode heidelibel,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
9,Ward Vercruysse,NaN,NaN,BDH_005,2014-05-08,Azuurwaterjuffer,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
10,Ward Vercruysse,NaN,NaN,BDH_005,2014-05-08,Blauwe glazenmaker,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
11,Ward Vercruysse,NaN,NaN,BDH_005,2014-05-08,Bruinrode heidelibel,NaN,NaN,4,2,NaN,1,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
12,Ward Vercruysse,NaN,NaN,BDH_005,2014-05-08,Lantaarntje,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
13,Ward Vercruysse,NaN,NaN,BDH_005,2014-05-08,Paardenbijter,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
14,Ward Vercruysse,NaN,NaN,BDH_006,2014-05-19,Azuurwaterjuffer,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
15,Ward Vercruysse,NaN,NaN,BDH_006,2014-05-19,Gaffelwaterjuffer,NaN,NaN,9,NaN,NaN,2,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
16,Ward Vercruysse,NaN,NaN,BDH_006,2014-05-19,Lantaarntje,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
17,Ward Vercruysse,NaN,NaN,BDH_006,2014-05-19,Platbuik,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
18,Ward Vercruysse,NaN,NaN,BDH_006,2014-05-19,Tengere grasjuffer,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
19,Ward Vercruysse,NaN,NaN,BDH_006,2014-05-19,Viervlek,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
20,Ward Vercruysse,NaN,NaN,BDH_006,2014-02-07,Bruinrode heidelibel,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
21,Ward Vercruysse,NaN,NaN,BDH_006,2014-02-07,Gaffelwaterjuffer,NaN,NaN,13,NaN,NaN,1,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
22,Ward Vercruysse,NaN,NaN,BDH_006,2014-02-07,Grote keizerlibel,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
23,Ward Vercruysse,NaN,NaN,BDH_006,2014-02-07,Lantaarntje,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
24,Ward Vercruysse,NaN,NaN,BDH_006,2014-02-07,Platbuik,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
25,Ward Vercruysse,NaN,NaN,BDH_006,2014-05-08,Bruinrode heidelibel,NaN,1,5,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
26,Ward Vercruysse,NaN,NaN,BDH_006,2014-05-08,Gaffelwaterjuffer,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
27,Ward Vercruysse,NaN,NaN,BDH_006,2014-05-08,Gewone oeverlibel,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
28,Ward Vercruysse,NaN,NaN,BDH_006,2014-05-08,Kleine roodoogjuffer,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
29,Ward Vercruysse,NaN,NaN,BDH_006,2014-05-08,Lantaarntje,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2638,Ward Vercruysse,NaN,NaN,ZWI_162,2013-07-15,Zwervende pantserjuffer,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2639,Ward Vercruysse,NaN,NaN,ZWI_164,2014-02-06,Bruinrode heidelibel,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2640,Ward Vercruysse,NaN,NaN,ZWI_164,2014-02-06,Gaffelwaterjuffer,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2641,Ward Vercruysse,NaN,NaN,ZWI_164,2014-02-06,Lantaarntje,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2642,Ward Vercruysse,NaN,NaN,ZWI_164,2014-01-07,Bruinrode heidelibel,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2643,Ward Vercruysse,NaN,NaN,ZWI_164,2014-01-09,Bruinrode heidelibel,NaN,NaN,2,NaN,NaN,3,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2644,Ward Vercruysse,NaN,NaN,ZWI_164,2014-01-09,Gewone pantserjuffer,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2645,Ward Vercruysse,NaN,NaN,ZWI_164,2014-01-09,Kleine roodoogjuffer,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2646,Ward Vercruysse,NaN,NaN,ZWI_164,2014-01-09,Lantaarntje,NaN,NaN,NaN,NaN,3,4,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2647,Ward Vercruysse,NaN,NaN,ZWI_164,2014-01-09,Paardenbijter,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2648,Ward Vercruysse,NaN,NaN,ZWI_164,2014-01-09,Tengere grasjuffer,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2649,Ward Vercruysse,NaN,NaN,ZWI_164,2014-01-09,Zwervende pantserjuffer,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2650,Ward Vercruysse,NaN,NaN,ZWI_165,2014-05-23,Azuurwaterjuffer,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2651,Ward Vercruysse,NaN,NaN,ZWI_165,2014-05-23,Bloedrode heidelibel,NaN,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2652,Ward Vercruysse,NaN,NaN,ZWI_165,2014-05-23,Gaffelwaterjuffer,NaN,NaN,2,1,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2653,Ward Vercruysse,NaN,NaN,ZWI_165,2014-05-23,Noordse witsnuitlibel,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2654,Ward Vercruysse,NaN,NaN,ZWI_165,2014-05-23,Viervlek,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2655,Ward Vercruysse,NaN,NaN,ZWI_165,2014-06-26,Bloedrode heidelibel,NaN,NaN,50,8,NaN,7,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2656,Ward Vercruysse,NaN,NaN,ZWI_165,2014-06-26,Bruinrode heidelibel,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2657,Ward Vercruysse,NaN,NaN,ZWI_165,2014-06-26,Gaffelwaterjuffer,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2658,Ward Vercruysse,NaN,NaN,ZWI_165,2014-06-26,Gewone oeverlibel,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2659,Ward Vercruysse,NaN,NaN,ZWI_165,2014-06-26,Grote keizerlibel,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2660,Ward Vercruysse,NaN,NaN,ZWI_165,2014-06-26,Zuidelijke heidelibel,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2661,Ward Vercruysse,NaN,NaN,ZWI_165,2014-08-13,Bloedrode heidelibel,NaN,NaN,9,2,NaN,2,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2662,Ward Vercruysse,NaN,NaN,ZWI_165,2014-08-13,Steenrode heidelibel,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2663,Ward Vercruysse,NaN,NaN,ZWI_165,2014-08-13,Zwervende pantserjuffer,NaN,NaN,2,1,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2664,Ward Vercruysse,NaN,NaN,ZWI_166,2014-02-06,Azuurwaterjuffer,NaN,NaN,6,NaN,NaN,2,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2665,Ward Vercruysse,NaN,NaN,ZWI_166,2014-02-06,Gaffelwaterjuffer,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2666,Ward Vercruysse,NaN,NaN,ZWI_166,2014-01-07,Bloedrode heidelibel,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO
2667,Ward Vercruysse,NaN,NaN,ZWI_166,2014-01-09,Bruinrode heidelibel,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO

In [19]:
import requests

In [20]:
def get_scientific_name(vernacular_name):
    """ """
    r = requests.get("".join(["http://api.gbif.org/v1/species/search?q=", vernacular_name]))
    try:
        name = r.json()['results'][0]['scientificName']    
        return name
    except:
        return ""

In [21]:
data["scientificName"] = data["SoortNaamNl"].apply(get_scientific_name)

In [23]:
sum(data["scientificName"]=="")

21

In [24]:
r = requests.get("http://api.gbif.org/v1/species/search?q=Azuurwaterjuffer")

In [25]:
r

In [26]:
r.json()['results'][0]['scientificName']

'Coenagrion puella Linnaeus, 1758'

In [ ]:
print (r)

In [27]:
data.head()

,WaarnemerNaam1,WaarnemerNaam2,WaarnemerNaam3,PoelCode,Datum,SoortNaamNl,Exuvium,Teneral,Mannetje,Wijfje,Adult onbepaald,Tandem,Eiafzettend,Opmerking_Poel,Opmerking_Soort,recordedBy,identifiedBy,institutionCode,scientificName
0,Ward Vercruysse,Simon Feys,NaN,BDH_004,2010-06-16,Azuurwaterjuffer,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,Ward Vercruysse | Simon Feys,Ward Vercruysse | Simon Feys,INBO,"Coenagrion puella Linnaeus, 1758"
1,Simon Feys,Ward Vercruysse,NaN,BDH_004,2010-07-19,Bloedrode heidelibel,NaN,NaN,8,3,NaN,NaN,NaN,NaN,"Tandems gezien, niet geteld",Simon Feys | Ward Vercruysse,Simon Feys | Ward Vercruysse,INBO,"Sympetrum sanguineum (Müller, 1764)"
2,Simon Feys,Ward Vercruysse,NaN,BDH_004,2010-07-19,Blauwe glazenmaker,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,Simon Feys | Ward Vercruysse,Simon Feys | Ward Vercruysse,INBO,"Aeshna cyanea Müller, 1764"
3,Ward Vercruysse,NaN,NaN,BDH_005,2014-05-19,Lantaarntje,NaN,NaN,NaN,1,NaN,NaN,x,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO,"Ischnura elegans Vander Linden, 1820"
4,Ward Vercruysse,NaN,NaN,BDH_005,2014-05-19,Azuurwaterjuffer,NaN,NaN,7,NaN,NaN,3,NaN,NaN,NaN,Ward Vercruysse,Ward Vercruysse,INBO,"Coenagrion puella Linnaeus, 1758"

In [ ]:
data.columns